### ISSUE TITLE
error: 'I2C_ERROR_OK' was not declared in this scope

### ISSUE THREAD

**Issue by gguereque** [bitixel/Omron_D6FPH#2]
Hello

I'm having the following error, when I compile "simple" example program without modifications:

`C:\Users\Guillermo\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getTemperature()':

C:\Users\Guillermo\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:104:44: error: 'I2C_ERROR_OK' was not declared in this scope

         if (_i2cPort->endTransmission() == I2C_ERROR_OK){

                                            ^

C:\Users\Guillermo\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::readRegister(uint8_t, uint16_t*)':

C:\Users\Guillermo\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:118:39: error: 'I2C_ERROR_OK' was not declared in this scope

     if(_i2cPort->endTransmission() == I2C_ERROR_OK){`

This basically in every function that has I2C_ERROR_OK.  Am I missing a library for this?

**Comment by leonefascia** [comment]
Hi
I am using an Arduino due. It seems like I get the same error as @gguereque, even if I use your new updated library (1.1.0). When I try to compile the file for Arduino uno than it works. However, I need it for my Arduino due.
Do you know where the problem could be? Thanks

**Comment by ACEngineering** [comment]
That used to be in ...hal_i2c.h

// External Wire.h equivalent error Codes
typedef enum {
    I2C_ERROR_OK=0,
    I2C_ERROR_DEV,
    I2C_ERROR_ACK,
    I2C_ERROR_TIMEOUT,
    I2C_ERROR_BUS,
    I2C_ERROR_BUSY,
    I2C_ERROR_MEMORY,
    I2C_ERROR_CONTINUE,
    I2C_ERROR_NO_BEGIN
} i2c_err_t;

But, it would seem that back in February, they changed all of the hardware definitions and left all of these out.
