### ISSUE TITLE
When using PlatformIO and ESP32 Hardware, building fails. 

### ISSUE THREAD

**Issue by jrodden1** [bitixel/Omron_D6FPH#3]
## Description 
When attempting to utilize this library in PlatformIO (inside VSCode on MacOS Monterey) on a project with **ESP32** hardware, I received the following build errors:

```
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::init()':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:56:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::isConnected()':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:61:43: error: 'I2C_ERROR_OK' was not declared in this scope
     return _i2cPort->endTransmission() == I2C_ERROR_OK;
                                           ^~~~~~~~~~~~
Compiling .pio/build/esp32dev/FrameworkArduino/USBMSC.cpp.o
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::executeMcuMode()':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:75:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
Compiling .pio/build/esp32dev/FrameworkArduino/WMath.cpp.o
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getPressure()':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:86:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
Compiling .pio/build/esp32dev/FrameworkArduino/WString.cpp.o
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getTemperature()':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:104:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
Compiling .pio/build/esp32dev/FrameworkArduino/base64.cpp.o
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::readRegister(uint8_t, uint16_t*)':
.pio/libdeps/esp32dev/Omron_D6FPH/src/Omron_D6FPH.cpp:118:39: error: 'I2C_ERROR_OK' was not declared in this scope
     if(_i2cPort->endTransmission() == I2C_ERROR_OK){
                                       ^~~~~~~~~~~~
Compiling .pio/build/esp32dev/FrameworkArduino/cbuf.cpp.o
Compiling .pio/build/esp32dev/FrameworkArduino/esp32-hal-adc.c.o
*** [.pio/build/esp32dev/lib540/Omron_D6FPH/Omron_D6FPH.cpp.o] Error 1
``` 

## Expected Behavior 
This library mentions that it should support `expressif32` ESP32 boards and so should build and upload to an ESP32. 

## Actual Behavior
Errors received as mentioned above in Description.  Unable to build or upload code to ESP32 hardware. 

## Proposed Solution
See PR: https://github.com/bitixel/Omron_D6FPH/pull/4#issue-1345345516

**Comment by brunodom** [comment]
@jrodden1 , by any chance, did you manage to solve this problem? I am still struggling to find a solution. Appreciate if you share what you did to fix it.

**Comment by jrodden1** [comment]
@brunodom I created a PR for the owner of the repo to fix it (but they will have to merge it into the master / main branch)

To get mine working, I manually edited the `src/Omron_D6FPH.h` file.  Line 33 was the culprit:

I changed this: 
```c
#if defined(__AVR__) || defined(ESP8266) 
```

To this: 
```c
#if defined(__AVR__) || defined(ESP8266) || defined(ESP32)
```

so that this enum would also get defined in the ESP32 environment
```c
enum {
    I2C_ERROR_OK=0,
    I2C_ERROR_LENGTH,
    I2C_ERROR_ADDRESS_SENT_NACK,
    I2C_ERROR_DATA_SENT_NACK,
    I2C_ERROR_OTHER
} i2c_err_t;
```

A visual of this fix diff can be seen in my commit here: 
https://github.com/bitixel/Omron_D6FPH/pull/4/commits/9cc5fe6f7d924378d0fc9d150a4b3d68fcd02925

If you manually make the changes to the library code in your dev environment version of the files, it should start working for you.  Hope this helps! 

- - - 
Alternatively, you could try using my forked version in which I fixed it: 
https://github.com/jrodden1/Omron_D6FPH and `git checkout` the `patch-1` branch

**Comment by brunodom** [comment]
@jrodden1 you rocks! I was getting crazy trying to solve, and you were precise! It is working here! Thanks a lot.

**Comment by bitixel** [comment]
Closing as, issue is fixed with https://github.com/bitixel/Omron_D6FPH/pull/4
