### ISSUE TITLE
Error while compiling with Arduino MKR

### ISSUE THREAD

**Issue by camparite** [bitixel/Omron_D6FPH#5]
Error while compiling the example:
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::init()':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:56:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:56:42: note: suggested alternative: 'USB_ERRORFLOW'
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
                                          USB_ERRORFLOW
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::isConnected()':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:61:43: error: 'I2C_ERROR_OK' was not declared in this scope
     return _i2cPort->endTransmission() == I2C_ERROR_OK;
                                           ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:61:43: note: suggested alternative: 'USB_ERRORFLOW'
     return _i2cPort->endTransmission() == I2C_ERROR_OK;
                                           ^~~~~~~~~~~~
                                           USB_ERRORFLOW
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::executeMcuMode()':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:75:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:75:42: note: suggested alternative: 'USB_ERRORFLOW'
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
                                          USB_ERRORFLOW
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getPressure()':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:86:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:86:44: note: suggested alternative: 'USB_ERRORFLOW'
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
                                            USB_ERRORFLOW
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getTemperature()':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:104:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:104:44: note: suggested alternative: 'USB_ERRORFLOW'
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
                                            USB_ERRORFLOW
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::readRegister(uint8_t, uint16_t*)':
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:118:39: error: 'I2C_ERROR_OK' was not declared in this scope
     if(_i2cPort->endTransmission() == I2C_ERROR_OK){
                                       ^~~~~~~~~~~~
c:\Users\matte\OneDrive\Documents\Arduino\libraries\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:118:39: note: suggested alternative: 'USB_ERRORFLOW'
     if(_i2cPort->endTransmission() == I2C_ERROR_OK){
                                       ^~~~~~~~~~~~
                                       USB_ERRORFLOW

exit status 1

Compilation error: exit status 1

**Comment by brunodom** [comment]
@camparite , did you find a solution for this problem? I am facing the same issue on my side.

**Comment by jrodden1** [comment]
@camparite, this looks like a similar problem as to my issue with ESP32s [here](https://github.com/bitixel/Omron_D6FPH/issues/3#issuecomment-1852549146l).

You could have a look at my PR that I made to fix the issue [here](https://github.com/bitixel/Omron_D6FPH/pull/4/commits/9cc5fe6f7d924378d0fc9d150a4b3d68fcd02925).     

Alternatively, you could try a 'hacky' fix  by adding the code block below before the code where you include the Omron library: 
```c
typedef enum {
    I2C_ERROR_OK=0,
    I2C_ERROR_LENGTH,
    I2C_ERROR_ADDRESS_SENT_NACK,
    I2C_ERROR_DATA_SENT_NACK,
    I2C_ERROR_OTHER
} i2c_err_t;
```

cc: @brunodom

**Comment by bitixel** [comment]
Closing as issue fixed with: https://github.com/bitixel/Omron_D6FPH/pull/4

**Comment by bitixel** [comment]
Closing as, issue is fixed with https://github.com/bitixel/Omron_D6FPH/pull/4
